package com.simealapps.simealape.collagelist;

import android.graphics.PointF;

import java.util.ArrayList;

import com.simealapps.simealape.R;

public class CollageThree extends Collage {
    public static int shapeCount = 3;

    public CollageThree(int i, int j) {
        this.collageLayoutList = new ArrayList();
        ArrayList obj = new ArrayList();
        obj.add(new PointF[]{new PointF(0.3333333f * ((float) i), ((float) j) * 1.0f), new PointF(0.3333333f * ((float) i), ((float) j) * 0.0f), new PointF(0.6666667f * ((float) i), ((float) j) * 0.0f), new PointF(0.6666667f * ((float) i), ((float) j) * 1.0f)});
        obj.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(0.3333333f * ((float) i), ((float) j) * 1.0f), new PointF(0.3333333f * ((float) i), ((float) j) * 0.0f), new PointF(((float) i) * 0.0f, ((float) j) * 0.0f)});
        obj.add(new PointF[]{new PointF(0.6666667f * ((float) i), ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f), new PointF(0.6666667f * ((float) i), ((float) j) * 0.0f)});
        this.collageLayoutList.add(new CollageLayout(obj));
        ArrayList obj2 = new ArrayList();
        obj2.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.0f, ((float) j) * 0.5f), new PointF(((float) i) * 1.0f, ((float) j) * 0.5f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f)});
        obj2.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 0.5f), new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.5f)});
        obj2.add(new PointF[]{new PointF(0.2f * ((float) i), 0.2f * ((float) j)), new PointF(0.2f * ((float) i), 0.8f * ((float) j)), new PointF(0.8f * ((float) i), 0.8f * ((float) j)), new PointF(0.8f * ((float) i), 0.2f * ((float) j))});
        CollageLayout obj3 = new CollageLayout(obj2);
        obj3.maskPairList.add(new MaskPair(2, R.drawable.mask_circle));
        obj3.setClearIndex(2);
        this.collageLayoutList.add(obj3);
        ArrayList obj4 = new ArrayList();
        obj4.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.0f, ((float) j) * 0.5f), new PointF(0.58f * ((float) i), ((float) j) * 0.5f), new PointF(0.58f * ((float) i), ((float) j) * 0.0f)});
        obj4.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 0.5f), new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(0.58f * ((float) i), ((float) j) * 1.0f), new PointF(0.58f * ((float) i), ((float) j) * 0.5f)});
        obj4.add(new PointF[]{new PointF(0.42f * ((float) i), 0.25f * ((float) j)), new PointF(0.42f * ((float) i), 0.75f * ((float) j)), new PointF(((float) i) * 1.0f, 0.75f * ((float) j)), new PointF(((float) i) * 1.0f, 0.25f * ((float) j))});
        CollageLayout obj5 = new CollageLayout(obj4);
        obj5.maskPairList.add(new MaskPair(0, R.drawable.mask_hexagon));
        obj5.maskPairList.add(new MaskPair(1, R.drawable.mask_hexagon));
        obj5.maskPairList.add(new MaskPair(2, R.drawable.mask_hexagon));
        this.collageLayoutList.add(obj5);
        ArrayList obj6 = new ArrayList();
        obj6.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(((float) i) * 0.5f, ((float) j) * 1.0f), new PointF(((float) i) * 0.5f, ((float) j) * 0.0f)});
        obj6.add(new PointF[]{new PointF(((float) i) * 0.5f, ((float) j) * 0.0f), new PointF(((float) i) * 0.5f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f)});
        obj6.add(new PointF[]{new PointF(0.25f * ((float) i), ((float) j) * 0.5f), new PointF(((float) i) * 0.5f, 0.75f * ((float) j)), new PointF(0.75f * ((float) i), ((float) j) * 0.5f), new PointF(((float) i) * 0.5f, 0.25f * ((float) j))});
        CollageLayout obj7 = new CollageLayout(obj6);
        obj7.setClearIndex(2);
        this.collageLayoutList.add(obj7);
        ArrayList obj8 = new ArrayList();
        obj8.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.0f, ((float) j) * 0.5f), new PointF(((float) i) * 1.0f, ((float) j) * 0.5f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f)});
        obj8.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 0.5f), new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.5f)});
        obj8.add(new PointF[]{new PointF(0.2f * ((float) i), 0.2f * ((float) j)), new PointF(0.2f * ((float) i), 0.8f * ((float) j)), new PointF(0.8f * ((float) i), 0.8f * ((float) j)), new PointF(0.8f * ((float) i), 0.2f * ((float) j))});
        CollageLayout obj9 = new CollageLayout(obj8);
        obj9.maskPairList.add(new MaskPair(2, R.drawable.mask_heart));
        obj9.setClearIndex(2);
        this.collageLayoutList.add(obj9);
        ArrayList obj10 = new ArrayList();
        obj10.add(new PointF[]{new PointF(((float) i) * 0.5f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.5f, ((float) j) * 0.0f)});
        obj10.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(((float) i) * 0.5f, ((float) j) * 1.0f), new PointF(((float) i) * 0.5f, ((float) j) * 0.5f), new PointF(((float) i) * 0.0f, ((float) j) * 0.5f)});
        obj10.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 0.5f), new PointF(((float) i) * 0.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.5f, ((float) j) * 0.0f), new PointF(((float) i) * 0.5f, ((float) j) * 0.5f)});
        this.collageLayoutList.add(new CollageLayout(obj10));
        ArrayList obj11 = new ArrayList();
        obj11.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(((float) i) * 0.5f, ((float) j) * 1.0f), new PointF(((float) i) * 0.5f, ((float) j) * 0.0f)});
        obj11.add(new PointF[]{new PointF(((float) i) * 0.5f, ((float) j) * 0.0f), new PointF(((float) i) * 0.5f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f)});
        obj11.add(new PointF[]{new PointF(0.2f * ((float) i), 0.2f * ((float) j)), new PointF(0.2f * ((float) i), 0.8f * ((float) j)), new PointF(0.8f * ((float) i), 0.8f * ((float) j)), new PointF(0.8f * ((float) i), 0.2f * ((float) j))});
        CollageLayout obj12 = new CollageLayout(obj11);
        obj12.maskPairList.add(new MaskPair(2, R.drawable.mask_hexagon));
        obj12.setClearIndex(2);
        this.collageLayoutList.add(obj12);
        ArrayList obj13 = new ArrayList();
        obj13.add(new PointF[]{new PointF(0.3333333f * ((float) i), ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f), new PointF(0.3333333f * ((float) i), ((float) j) * 0.0f)});
        obj13.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(0.3333333f * ((float) i), ((float) j) * 1.0f), new PointF(0.3333333f * ((float) i), ((float) j) * 0.5f), new PointF(((float) i) * 0.0f, ((float) j) * 0.5f)});
        obj13.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 0.5f), new PointF(((float) i) * 0.0f, ((float) j) * 0.0f), new PointF(0.3333333f * ((float) i), ((float) j) * 0.0f), new PointF(0.3333333f * ((float) i), ((float) j) * 0.5f)});
        this.collageLayoutList.add(new CollageLayout(obj13));
        ArrayList obj14 = new ArrayList();
        obj14.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(((float) i) * 0.5f, ((float) j) * 1.0f), new PointF(((float) i) * 0.5f, ((float) j) * 0.0f)});
        obj14.add(new PointF[]{new PointF(((float) i) * 0.5f, ((float) j) * 0.0f), new PointF(((float) i) * 0.5f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f)});
        obj14.add(new PointF[]{new PointF(0.2f * ((float) i), 0.2f * ((float) j)), new PointF(0.2f * ((float) i), 0.8f * ((float) j)), new PointF(0.8f * ((float) i), 0.8f * ((float) j)), new PointF(0.8f * ((float) i), 0.2f * ((float) j))});
        CollageLayout obj15 = new CollageLayout(obj14);
        obj15.maskPairList.add(new MaskPair(2, R.drawable.mask_circle));
        obj15.setClearIndex(2);
        this.collageLayoutList.add(obj15);
        ArrayList obj16 = new ArrayList();
        obj16.add(new PointF[]{new PointF(((float) i) * 0.5f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.5f, ((float) j) * 0.0f)});
        obj16.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(((float) i) * 0.5f, ((float) j) * 1.0f), new PointF(((float) i) * 0.5f, 0.6666667f * ((float) j)), new PointF(((float) i) * 0.0f, 0.6666667f * ((float) j))});
        obj16.add(new PointF[]{new PointF(((float) i) * 0.0f, 0.6666667f * ((float) j)), new PointF(((float) i) * 0.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.5f, ((float) j) * 0.0f), new PointF(((float) i) * 0.5f, 0.6666667f * ((float) j))});
        this.collageLayoutList.add(new CollageLayout(obj16));
        ArrayList obj17 = new ArrayList();
        obj17.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.0f, ((float) j) * 0.5f), new PointF(((float) i) * 1.0f, ((float) j) * 0.5f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f)});
        obj17.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 0.5f), new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.5f)});
        obj17.add(new PointF[]{new PointF(0.2f * ((float) i), 0.25f * ((float) j)), new PointF(0.2f * ((float) i), 0.75f * ((float) j)), new PointF(0.8f * ((float) i), 0.75f * ((float) j)), new PointF(0.8f * ((float) i), 0.25f * ((float) j))});
        CollageLayout obj18 = new CollageLayout(obj17);
        obj18.setClearIndex(2);
        this.collageLayoutList.add(obj18);
        ArrayList obj19 = new ArrayList();
        obj19.add(new PointF[]{new PointF(0.6666667f * ((float) i), ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f), new PointF(0.6666667f * ((float) i), ((float) j) * 0.0f)});
        obj19.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(0.6666667f * ((float) i), ((float) j) * 1.0f), new PointF(0.6666667f * ((float) i), ((float) j) * 0.5f), new PointF(((float) i) * 0.0f, ((float) j) * 0.5f)});
        obj19.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 0.5f), new PointF(((float) i) * 0.0f, ((float) j) * 0.0f), new PointF(0.6666667f * ((float) i), ((float) j) * 0.0f), new PointF(0.6666667f * ((float) i), ((float) j) * 0.5f)});
        this.collageLayoutList.add(new CollageLayout(obj19));
        ArrayList obj20 = new ArrayList();
        obj20.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(((float) i) * 0.5f, ((float) j) * 1.0f), new PointF(((float) i) * 0.5f, ((float) j) * 0.0f), new PointF(((float) i) * 0.0f, ((float) j) * 0.0f)});
        obj20.add(new PointF[]{new PointF(((float) i) * 0.5f, ((float) j) * 0.0f), new PointF(((float) i) * 0.5f, ((float) j) * 0.5f), new PointF(((float) i) * 1.0f, ((float) j) * 0.5f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f)});
        obj20.add(new PointF[]{new PointF(((float) i) * 0.5f, ((float) j) * 0.5f), new PointF(((float) i) * 0.5f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.5f)});
        this.collageLayoutList.add(new CollageLayout(obj20));
        ArrayList obj21 = new ArrayList();
        obj21.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(((float) i) * 0.5f, ((float) j) * 1.0f), new PointF(((float) i) * 0.5f, ((float) j) * 0.0f)});
        obj21.add(new PointF[]{new PointF(((float) i) * 0.5f, ((float) j) * 0.0f), new PointF(((float) i) * 0.5f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f)});
        obj21.add(new PointF[]{new PointF(0.2f * ((float) i), 0.25f * ((float) j)), new PointF(0.2f * ((float) i), 0.75f * ((float) j)), new PointF(0.8f * ((float) i), 0.75f * ((float) j)), new PointF(0.8f * ((float) i), 0.25f * ((float) j))});
        CollageLayout obj22 = new CollageLayout(obj21);
        obj22.setClearIndex(2);
        this.collageLayoutList.add(obj22);
        ArrayList obj23 = new ArrayList();
        obj23.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(0.3333333f * ((float) i), ((float) j) * 1.0f), new PointF(0.3333333f * ((float) i), ((float) j) * 0.0f), new PointF(((float) i) * 0.0f, ((float) j) * 0.0f)});
        obj23.add(new PointF[]{new PointF(0.3333333f * ((float) i), ((float) j) * 0.0f), new PointF(0.3333333f * ((float) i), ((float) j) * 0.5f), new PointF(((float) i) * 1.0f, ((float) j) * 0.5f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f)});
        obj23.add(new PointF[]{new PointF(0.3333333f * ((float) i), ((float) j) * 0.5f), new PointF(0.3333333f * ((float) i), ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.5f)});
        this.collageLayoutList.add(new CollageLayout(obj23));
        ArrayList obj24 = new ArrayList();
        obj24.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(0.6666667f * ((float) i), ((float) j) * 1.0f), new PointF(0.6666667f * ((float) i), ((float) j) * 0.0f), new PointF(((float) i) * 0.0f, ((float) j) * 0.0f)});
        obj24.add(new PointF[]{new PointF(0.6666667f * ((float) i), ((float) j) * 0.0f), new PointF(0.6666667f * ((float) i), ((float) j) * 0.5f), new PointF(((float) i) * 1.0f, ((float) j) * 0.5f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f)});
        obj24.add(new PointF[]{new PointF(0.6666667f * ((float) i), ((float) j) * 0.5f), new PointF(0.6666667f * ((float) i), ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.5f)});
        this.collageLayoutList.add(new CollageLayout(obj24));
        ArrayList obj25 = new ArrayList();
        obj25.add(new PointF[]{new PointF(((float) i) * 0.0f, 0.3333333f * ((float) j)), new PointF(((float) i) * 1.0f, 0.3333333f * ((float) j)), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.0f, ((float) j) * 0.0f)});
        obj25.add(new PointF[]{new PointF(((float) i) * 0.0f, 0.6666667f * ((float) j)), new PointF(((float) i) * 0.0f, 0.3333333f * ((float) j)), new PointF(((float) i) * 1.0f, 0.3333333f * ((float) j)), new PointF(((float) i) * 1.0f, 0.6666667f * ((float) j))});
        obj25.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(((float) i) * 0.0f, 0.6666667f * ((float) j)), new PointF(((float) i) * 1.0f, 0.6666667f * ((float) j)), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f)});
        this.collageLayoutList.add(new CollageLayout(obj25));
        ArrayList obj26 = new ArrayList();
        obj26.add(new PointF[]{new PointF(((float) i) * 0.0f, 0.3333333f * ((float) j)), new PointF(((float) i) * 1.0f, 0.3333333f * ((float) j)), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.0f, ((float) j) * 0.0f)});
        obj26.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(((float) i) * 0.5f, ((float) j) * 1.0f), new PointF(((float) i) * 0.5f, 0.3333333f * ((float) j)), new PointF(((float) i) * 0.0f, 0.3333333f * ((float) j))});
        obj26.add(new PointF[]{new PointF(((float) i) * 0.5f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, 0.3333333f * ((float) j)), new PointF(((float) i) * 0.5f, 0.3333333f * ((float) j))});
        this.collageLayoutList.add(new CollageLayout(obj26));
        ArrayList obj27 = new ArrayList();
        obj27.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.5f), new PointF(((float) i) * 0.0f, ((float) j) * 0.5f)});
        obj27.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 0.5f), new PointF(((float) i) * 0.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.5f, ((float) j) * 0.0f), new PointF(((float) i) * 0.5f, ((float) j) * 0.5f)});
        obj27.add(new PointF[]{new PointF(((float) i) * 0.5f, ((float) j) * 0.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.5f), new PointF(((float) i) * 0.5f, ((float) j) * 0.5f)});
        this.collageLayoutList.add(new CollageLayout(obj27));
        ArrayList obj28 = new ArrayList();
        obj28.add(new PointF[]{new PointF(((float) i) * 0.0f, 0.25f * ((float) j)), new PointF(((float) i) * 1.0f, 0.25f * ((float) j)), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.0f, ((float) j) * 0.0f)});
        obj28.add(new PointF[]{new PointF(((float) i) * 0.0f, 0.75f * ((float) j)), new PointF(((float) i) * 0.0f, 0.25f * ((float) j)), new PointF(((float) i) * 1.0f, 0.25f * ((float) j)), new PointF(((float) i) * 1.0f, 0.75f * ((float) j))});
        obj28.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(((float) i) * 0.0f, 0.75f * ((float) j)), new PointF(((float) i) * 1.0f, 0.75f * ((float) j)), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f)});
        this.collageLayoutList.add(new CollageLayout(obj28));
        ArrayList obj29 = new ArrayList();
        obj29.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, 0.6666667f * ((float) j)), new PointF(((float) i) * 0.0f, 0.6666667f * ((float) j))});
        obj29.add(new PointF[]{new PointF(((float) i) * 0.0f, 0.6666667f * ((float) j)), new PointF(((float) i) * 0.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.5f, ((float) j) * 0.0f), new PointF(((float) i) * 0.5f, 0.6666667f * ((float) j))});
        obj29.add(new PointF[]{new PointF(((float) i) * 0.5f, ((float) j) * 0.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f), new PointF(((float) i) * 1.0f, 0.6666667f * ((float) j)), new PointF(((float) i) * 0.5f, 0.6666667f * ((float) j))});
        this.collageLayoutList.add(new CollageLayout(obj29));
        ArrayList obj30 = new ArrayList();
        obj30.add(new PointF[]{new PointF(((float) i) * 0.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, ((float) j) * 1.0f), new PointF(((float) i) * 1.0f, 0.3333333f * ((float) j)), new PointF(((float) i) * 0.0f, 0.3333333f * ((float) j))});
        obj30.add(new PointF[]{new PointF(((float) i) * 0.0f, 0.3333333f * ((float) j)), new PointF(((float) i) * 0.0f, ((float) j) * 0.0f), new PointF(((float) i) * 0.5f, ((float) j) * 0.0f), new PointF(((float) i) * 0.5f, 0.3333333f * ((float) j))});
        obj30.add(new PointF[]{new PointF(((float) i) * 0.5f, ((float) j) * 0.0f), new PointF(((float) i) * 1.0f, ((float) j) * 0.0f), new PointF(((float) i) * 1.0f, 0.3333333f * ((float) j)), new PointF(((float) i) * 0.5f, 0.3333333f * ((float) j))});
        this.collageLayoutList.add(new CollageLayout(obj30));
    }
}
